# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time_use',
            field=models.DateTimeField(null=True, verbose_name='时间'),
        ),
    ]
