# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-14 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20170427_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_self_id', models.IntegerField(verbose_name='\u5458\u5de5\u7f16\u53f7')),
                ('name', models.CharField(max_length=255, verbose_name='\u59d3\u540d')),
                ('gender', models.IntegerField(choices=[(0, b'\xe5\xa5\xb3'), (1, b'\xe7\x94\xb7')], verbose_name='\u6027\u522b')),
                ('age', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, b'\xe5\xa5\xb3'), (1, b'\xe7\x94\xb7')], verbose_name='\u72b6\u6001')),
                ('join_time', models.DateTimeField(null=True, verbose_name='\u5165\u804c\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5458\u5de5',
                'db_table': 'staff',
                'managed': True,
                'verbose_name_plural': '\u5458\u5de5',
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': True, 'verbose_name': '\u623f\u95f4', 'verbose_name_plural': '\u623f\u95f4'},
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='abc', max_length=255, verbose_name='\u623f\u95f4\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(default=123, verbose_name='\u623f\u95f4\u7f16\u53f7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='is_use',
            field=models.BooleanField(verbose_name=b'\xe5\x8d\xa0\xe7\x94\xa8'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[(b'small', b'\xe5\xb0\x8f\xe5\x8c\x85'), (b'middle', b'\xe4\xb8\xad\xe5\x8c\x85'), (b'large', b'\xe5\xa4\xa7\xe5\x8c\x85')], max_length=10, verbose_name=b'\xe7\xa7\x8d\xe7\xb1\xbb'),
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
